import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:scribocracy_new/models/note.dart';
import 'package:intl/intl.dart';

class PdfGenerator {
  
  static Future<void> generateAndPrint(Note note) async {
    final doc = pw.Document();

    // 1. Chargement de la police (On utilise une police standard pour le PDF pour éviter les bugs de chargement)
    // Si vous voulez Orbitron dans le PDF, il faut le charger via rootBundle, mais pour l'instant restons simple et robuste.
    final fontBold = await PdfGoogleFonts.orbitronBold();
    final fontMono = await PdfGoogleFonts.shareTechMonoRegular();

    // 2. Préparation des images
    List<pw.Widget> pdfImages = [];
    for (String path in note.images) {
      final file = File(path);
      if (await file.exists()) {
        final imageBytes = await file.readAsBytes();
        final image = pw.MemoryImage(imageBytes);
        pdfImages.add(
          pw.Container(
            margin: const pw.EdgeInsets.only(bottom: 20),
            decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.black, width: 2)),
            child: pw.Image(image, fit: pw.BoxFit.contain, height: 300),
          )
        );
      }
    }

    // 3. Construction de la page
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (pw.Context context) {
          return [
            // HEADER "TOP SECRET"
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text("SCRIBOCRACY_INTEL // EXFIL_V2", style: pw.TextStyle(font: fontMono, fontSize: 10, color: PdfColors.grey700)),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
                  decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.red, width: 2)),
                  child: pw.Text("CONFIDENTIAL / EYES ONLY", style: pw.TextStyle(font: fontBold, color: PdfColors.red, fontSize: 12)),
                ),
              ],
            ),
            pw.SizedBox(height: 20),
            pw.Divider(color: PdfColors.black, thickness: 2),
            pw.SizedBox(height: 20),

            // METADATA (Date, GPS, Tags)
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      _buildMetaRow("TIMESTAMP", DateFormat('yyyy-MM-dd HH:mm:ss').format(note.modifiedTime), fontMono),
                      if (note.latitude != null)
                        _buildMetaRow("COORDINATES", "${note.latitude!.toStringAsFixed(5)} / ${note.longitude!.toStringAsFixed(5)}", fontMono),
                      _buildMetaRow("AGENT_ID", "NETRUNNER_01", fontMono),
                    ],
                  )
                ),
                // TAGS
                if (note.tags.isNotEmpty)
                  pw.Wrap(
                    spacing: 5,
                    children: note.tags.map((t) => pw.Container(
                      padding: const pw.EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                      color: PdfColors.black,
                      child: pw.Text(t, style: pw.TextStyle(font: fontBold, color: PdfColors.white, fontSize: 8)),
                    )).toList()
                  )
              ],
            ),
            
            pw.SizedBox(height: 30),

            // TITRE
            pw.Text(note.title.toUpperCase(), style: pw.TextStyle(font: fontBold, fontSize: 24)),
            pw.SizedBox(height: 10),
            pw.Container(height: 1, color: PdfColors.black),
            pw.SizedBox(height: 20),

            // CONTENU
            pw.Text(
              note.content,
              style: pw.TextStyle(font: fontMono, fontSize: 12, lineSpacing: 1.5),
              textAlign: pw.TextAlign.justify,
            ),

            pw.SizedBox(height: 30),

            // IMAGES
            if (pdfImages.isNotEmpty) ...[
              pw.Text("ATTACHED EVIDENCE:", style: pw.TextStyle(font: fontBold, fontSize: 14, decoration: pw.TextDecoration.underline)),
              pw.SizedBox(height: 15),
              ...pdfImages
            ],

            pw.Spacer(),
            
            // FOOTER
            pw.Divider(color: PdfColors.grey),
            pw.Center(
              child: pw.Text("GENERATED BY SCRIBOCRACY // SECURE CHANNEL", style: pw.TextStyle(font: fontMono, fontSize: 8, color: PdfColors.grey)),
            )
          ];
        },
      ),
    );

    // 4. Lancer l'interface de partage/impression
    await Printing.sharePdf(bytes: await doc.save(), filename: 'intel_report_${DateTime.now().millisecondsSinceEpoch}.pdf');
  }

  static pw.Widget _buildMetaRow(String label, String value, pw.Font font) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 5),
      child: pw.RichText(
        text: pw.TextSpan(
          children: [
            pw.TextSpan(text: "$label: ", style: pw.TextStyle(font: font, fontWeight: pw.FontWeight.bold)),
            pw.TextSpan(text: value, style: pw.TextStyle(font: font)),
          ],
        ),
      ),
    );
  }
}